# Generated by Django 6.0.5 on 2026-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_student_courses_subject_student_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
